/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dropwizard.scaffolding.entrypoint;

import dropwizard.scaffolding.common.config.ImmutableCommonConfig;
import dropwizard.scaffolding.entrypoint.modules.ConfigurationModule;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    ApplicationComponent applicationComponent =
        DaggerApplicationComponent.builder()
            .configurationModule(
                new ConfigurationModule(ImmutableCommonConfig.builder().foo("xalala").build()))
            .build();
    System.out.println(new App().getGreeting());
  }
}
